- name: Ensure iptables is installed and updated
  apt: name=iptables state=latest
  become: yes
  when: ensured_apps

- name: Allow ssh
  iptables:
    chain: INPUT
    protocol: tcp
    destination_port: 22
    jump: ACCEPT
  with_items:
    INPUT
  become: yes

- name: Allow related and established connections
  iptables:
    chain: INPUT
    ctstate: ESTABLISHED,RELATED
    jump: ACCEPT
  become: yes

- name: Set policy to drop incoming and forward
  iptables:
    chain: "{{ item }}"
    policy: DROP
  with_items:
    - INPUT
    - FORWARD
  become: yes
