- block:
  - name: Install applications
    apt: name={{ item }} state=latest
    with_items:
      - postfix
      - spamassassin
  - name: Add templates
    template: src=templates/{{ item }} dest=/etc/postfix/{{ item }}
    with_items:
      - main.cf
      - master.cf
  - name: Check services
    service: name={{ item }} state=started enabled=True
    with_items:
      - postfix
      - spamassassin
  become: yes
  when: main_apps
